#!/bin/bash
# setup_agent.sh
# Purpose: Create a limited "openclaw-agent" user, install recommended tools,
# configure SSH public-key auth, set up a restricted sudoers entry for specific commands,
# and create a simple logging mechanism for actions the agent might perform.
#
# IMPORTANT: This script must be reviewed before running. It makes system changes
# (creates a user, edits sudoers). Run on macOS with Administrator privileges.
#
# Usage (run as an admin user):
#   chmod +x setup_agent.sh
#   sudo ./setup_agent.sh /path/to/public_key.pub
#
# Arguments:
#   $1 = path to the public key file (ED25519 recommended). If omitted, the script
#        creates the user but does not install keys.
#
set -euo pipefail
PUBKEY_PATH="${1:-}" 
AGENT_USER="openclaw-agent"
AGENT_HOME="/Users/${AGENT_USER}"
LOG_DIR="/var/log/openclaw-agent"
SUDOERS_FILE="/etc/sudoers.d/${AGENT_USER}"
ALLOWED_COMMANDS=("/usr/local/bin/openclaw" "/usr/bin/installer" "/usr/sbin/softwareupdate" "/usr/bin/ditto" "/usr/bin/defaults")

echo ">>> This script will:
 - create user: ${AGENT_USER}
 - create log dir: ${LOG_DIR}
 - optionally install SSH public key from: ${PUBKEY_PATH:-<none provided>}
 - create sudoers file to allow limited commands (see below)
 - install Homebrew + Node.js + Playwright (optional step, commented out)
"

# 1) Create user (macOS)
if id "${AGENT_USER}" &>/dev/null; then
  echo "User ${AGENT_USER} already exists. Skipping user creation."
else
  echo "Creating user ${AGENT_USER}..."
  sudo /usr/bin/sysadminctl -addUser ${AGENT_USER} -fullName "OpenClaw Agent" -password "" -home ${AGENT_HOME} || true
  # Ensure the home directory exists and correct ownership
  sudo mkdir -p "${AGENT_HOME}"
  sudo chown -R ${AGENT_USER}:staff "${AGENT_HOME}"
  echo "Created user ${AGENT_USER} (home: ${AGENT_HOME}). Note: no password set; use SSH key auth."
fi

# 2) SSH setup
if [ -n "${PUBKEY_PATH}" ] && [ -f "${PUBKEY_PATH}" ]; then
  echo "Installing public key to ${AGENT_USER} authorized_keys..."
  sudo mkdir -p "${AGENT_HOME}/.ssh"
  sudo chmod 700 "${AGENT_HOME}/.ssh"
  sudo cp "${PUBKEY_PATH}" "${AGENT_HOME}/.ssh/authorized_keys"
  sudo chown ${AGENT_USER}:staff "${AGENT_HOME}/.ssh/authorized_keys"
  sudo chmod 600 "${AGENT_HOME}/.ssh/authorized_keys"
  echo "Public key installed."
else
  echo "No public key provided or file not found. Skipping key installation."
fi

# 3) Create logging directory
if [ ! -d "${LOG_DIR}" ]; then
  echo "Creating log directory ${LOG_DIR}..."
  sudo mkdir -p "${LOG_DIR}"
  sudo chown root:admin "${LOG_DIR}"
  sudo chmod 750 "${LOG_DIR}"
fi

# 4) Create sudoers file with limited commands
echo "Setting up sudoers file: ${SUDOERS_FILE}"
SUDOERS_CONTENT="${AGENT_USER} ALL=(ALL) NOPASSWD: \\
"
for cmd in "${ALLOWED_COMMANDS[@]}"; do
  SUDOERS_CONTENT+="\t${cmd},\\\n"
done
# Also allow tail, cat for log reading
SUDOERS_CONTENT+="\t/bin/cat, /usr/bin/tail -n 500 /var/log/openclaw.log\n"

# Write sudoers file
echo "# Auto-generated by setup_agent.sh" | sudo tee "${SUDOERS_FILE}" >/dev/null
echo "${SUDOERS_CONTENT}" | sudo tee -a "${SUDOERS_FILE}" >/dev/null
sudo chmod 440 "${SUDOERS_FILE}"

# 5) Optional: install Homebrew + Node (commented and safe to run manually)
cat <<'EOF'

# NOTE: The following installation steps are commented out. Review and run manually if desired.
# To enable them, remove the leading ':' and the surrounding comments.

: <<'DISABLE_INSTALL'
# Install Homebrew (if not installed)
if ! command -v brew >/dev/null 2>&1; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
# Install Node.js (LTS)
brew install node
# Install Playwright for browser automation
npm install -g playwright
# Optionally install playwright browsers
npx playwright install --with-deps
DISABLE_INSTALL

EOF

# 6) Create a minimal wrapper script for logging agent actions
AGENT_LOGGER="/usr/local/bin/openclaw-agent-log"
sudo tee ${AGENT_LOGGER} >/dev/null <<'SH'
#!/bin/bash
# Simple logger wrapper: records timestamp, user, and command to agent log
LOGFILE="/var/log/openclaw-agent/agent-actions.log"
mkdir -p "$(dirname "$LOGFILE")"
cmd="$@"
echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') | $(whoami) | ${AGENT_USER} | $cmd" >> "$LOGFILE"
# Execute the command
exec "$@"
SH
sudo chmod 755 ${AGENT_LOGGER}

# 7) Final notes and instructions for admin
cat <<NOTES

Setup complete (script ran). Manual steps you should perform or verify:

1) Verify the sudoers file at: ${SUDOERS_FILE}
   - Edit if you want to add/remove allowed commands. Do NOT break sudoers syntax.

2) If you want passwordless SSH only, ensure in /etc/ssh/sshd_config:
   - PasswordAuthentication no
   - ChallengeResponseAuthentication no
   - PubkeyAuthentication yes
   Then restart SSH (careful if remote).

3) If you didn't provide a public key, add one now to ${AGENT_HOME}/.ssh/authorized_keys
   and set ownership/permissions: chown ${AGENT_USER}:staff ${AGENT_HOME}/.ssh -R && chmod 700 ${AGENT_HOME}/.ssh && chmod 600 ${AGENT_HOME}/.ssh/authorized_keys

4) Review the commented installation block (Homebrew/Node/Playwright) and run manually if you want those tools installed.

5) To revoke agent access: remove the public key from authorized_keys or remove the ${AGENT_USER} account.

Security reminder: Do not paste private keys or passwords into chat. This script should be reviewed before run.

NOTES

echo "All done."
